import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { BsChevronCompactRight } from "react-icons/bs";
import { RxTriangleDown, RxTriangleUp } from "react-icons/rx";
import Header from "../components/Header";
import { useEffect, useState } from "react";

export default function Home() {
  const [transactions, setTransactions] = useState([]);

  useEffect(() => {
    const fetchTransactions = async () => {
      const res = await fetch("/api/transactions");
      const data = await res.json();
      setTransactions(data);
    };
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div>
        <h1>All Transactions</h1>
        {transactions.length === 0 ? (
          <div>Loading ...</div>
        ) : (
          transactions.map((transaction) => (
            <div key={transaction.id}>
              <p>{transaction.date}</p>
            </div>
          ))
        )}
      </div>

      <section className="bg-gray-100">
        <div className="flex flex-col min-h-screen">
          <div className="flex justify-start items-center text-3xl">
            <p className="fixed top-30">FEBRUARY</p>
          </div>
          {/* indiv. card  */}
          <div className="flex mt-6">
            {/* date div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2">
              <p className="text-5xl">5</p>
            </div>
            {/* end date div  */}
            {/* balance div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2 flex">
              <div>
                <p>
                  Balance
                  <br />
                  <span className="text-green-500">$0.00</span>
                </p>
              </div>
              <div>
                <BsChevronCompactRight className="text-5xl" />
              </div>
            </div>
          </div>
          {/* end balance div  */}

          {/* end individual card  */}

          {/* indiv. card  */}
          <div className="flex mt-2">
            {/* date div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2">
              <p className="text-5xl">6</p>
            </div>
            {/* end date div  */}
            {/* balance and transactions divdiv  */}

            <div className="bg-white p-6 rounded-lg shadow-lg flex">
              <div className="mr-4">
                <div className="flex flex-col justify-between">
                  <div>
                    <p>
                      Balance
                      <br />
                      <span className="text-green-500">$304</span>
                    </p>
                  </div>
                  <div className="mt-14">
                    <p>
                      <RxTriangleUp className="text-green-500" /> $303
                    </p>
                  </div>
                </div>

                {/* end balance div  */}
              </div>
              <div className="flex flex-col">
                <h2 className="underline">Transactions</h2>
                <table>
                  <tr>
                    <td>Pay</td>
                    <td className="text-green-500">$850</td>
                  </tr>
                  <tr>
                    <td>Rent</td>
                    <td className="text-red-500">$410</td>
                  </tr>
                  <tr>
                    <td>Dave</td>
                    <td className="text-red-500">$137</td>
                  </tr>
                  <tr>
                    <td colSpan={2}>&nbsp;</td>
                  </tr>
                  <tr>
                    <td className="font-bold">total:</td>
                    <td className="text-green-500">$303</td>
                  </tr>
                </table>
              </div>
            </div>
          </div>

          {/* end individual card  */}

          {/* indiv. card  */}
          <div className="flex mt-2">
            {/* date div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2">
              <p className="text-5xl">7</p>
            </div>
            {/* end date div  */}
            {/* balance div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2 flex">
              <div>
                <p>
                  Balance
                  <br />
                  <span className="text-green-500">$303</span>
                </p>
              </div>
              <div>
                <BsChevronCompactRight className="text-5xl" />
              </div>
            </div>
          </div>
          {/* end balance div  */}

          {/* end individual card  */}

          {/* indiv. card  */}
          <div className="flex mt-2">
            {/* date div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2">
              <p className="text-5xl">8</p>
            </div>
            {/* end date div  */}
            {/* balance div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2 flex">
              <div>
                <p>
                  Balance
                  <br />
                  <span className="text-green-500">$$303</span>
                </p>
              </div>
              <div>
                <BsChevronCompactRight className="text-5xl" />
              </div>
            </div>
          </div>
          {/* end balance div  */}

          {/* end individual card  */}

          {/* indiv. card  */}
          <div className="flex mt-2">
            {/* date div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2">
              <p className="text-5xl">9</p>
            </div>
            {/* end date div  */}
            {/* balance div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2 flex">
              <div>
                <p>
                  Balance
                  <br />
                  <span className="text-green-500">$303</span>
                </p>
              </div>
              <div>
                <BsChevronCompactRight className="text-5xl" />
              </div>
            </div>
            {/* end balance div  */}
          </div>
          {/* end card  */}

          {/* indiv. card  */}
          <div className="flex mt-2">
            {/* date div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2">
              <p className="text-5xl">10</p>
            </div>
            {/* end date div  */}
            {/* balance div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2 flex">
              <div>
                <p>
                  Balance
                  <br />
                  <span className="text-green-500">$303</span>
                </p>
              </div>
              <div>
                <BsChevronCompactRight className="text-5xl" />
              </div>
            </div>
            {/* end balance div  */}
          </div>
          {/* end card  */}

          {/* indiv. card  */}
          <div className="flex mt-2">
            {/* date div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2">
              <p className="text-5xl">11</p>
            </div>
            {/* end date div  */}
            {/* balance div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2 flex">
              <div>
                <p>
                  Balance
                  <br />
                  <span className="text-green-500">$303</span>
                </p>
              </div>
              <div>
                <BsChevronCompactRight className="text-5xl" />
              </div>
            </div>
            {/* end balance div  */}
          </div>
          {/* end card  */}

          {/* indiv. card  */}
          <div className="flex mt-2">
            {/* date div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2">
              <p className="text-5xl">12</p>
            </div>
            {/* end date div  */}
            {/* balance and transactions divdiv  */}

            <div className="bg-white p-6 rounded-lg shadow-lg flex">
              <div className="mr-4">
                <div className="flex flex-col justify-between">
                  <div>
                    <p>
                      Balance
                      <br />
                      <span className="text-green-500">$184.54</span>
                    </p>
                  </div>
                  <div className="mt-14">
                    <p>
                      <RxTriangleDown className="text-red-500" /> $118.46
                    </p>
                  </div>
                </div>

                {/* end balance div  */}
              </div>
              <div className="flex flex-col">
                <h2 className="underline">Transactions</h2>
                <table>
                  <tr>
                    <td>Progressive</td>
                    <td className="text-red-500">$118.46</td>
                  </tr>
                  <tr>
                    <td colSpan={2}>&nbsp;</td>
                  </tr>
                  <tr>
                    <td className="font-bold">total:</td>
                    <td className="text-red-500">$118.46</td>
                  </tr>
                </table>
              </div>
            </div>
          </div>

          {/* end individual card  */}

          {/* indiv. card  */}
          <div className="flex mt-2">
            {/* date div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2">
              <p className="text-5xl">13</p>
            </div>
            {/* end date div  */}
            {/* balance div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2 flex">
              <div>
                <p>
                  Balance
                  <br />
                  <span className="text-green-500">$184.54</span>
                </p>
              </div>
              <div>
                <BsChevronCompactRight className="text-5xl" />
              </div>
            </div>
            {/* end balance div  */}
          </div>
          {/* end card  */}

          {/* indiv. card  */}
          <div className="flex mt-2">
            {/* date div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2">
              <p className="text-5xl">14</p>
            </div>
            {/* end date div  */}
            {/* balance div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2 flex">
              <div>
                <p>
                  Balance
                  <br />
                  <span className="text-green-500">$184.54</span>
                </p>
              </div>
              <div>
                <BsChevronCompactRight className="text-5xl" />
              </div>
            </div>
            {/* end balance div  */}
          </div>
          {/* end card  */}

          {/* indiv. card  */}
          <div className="flex mt-2">
            {/* date div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2">
              <p className="text-5xl">15</p>
            </div>
            {/* end date div  */}
            {/* balance div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2 flex">
              <div>
                <p>
                  Balance
                  <br />
                  <span className="text-green-500">$184.54</span>
                </p>
              </div>
              <div>
                <BsChevronCompactRight className="text-5xl" />
              </div>
            </div>
            {/* end balance div  */}
          </div>
          {/* end card  */}

          {/* indiv. card  */}
          <div className="flex mt-2">
            {/* date div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2">
              <p className="text-5xl">16</p>
            </div>
            {/* end date div  */}
            {/* balance div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2 flex">
              <div>
                <p>
                  Balance
                  <br />
                  <span className="text-green-500">$184.54</span>
                </p>
              </div>
              <div>
                <BsChevronCompactRight className="text-5xl" />
              </div>
            </div>
            {/* end balance div  */}
          </div>
          {/* end card  */}

          {/* indiv. card  */}
          <div className="flex mt-2">
            {/* date div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2">
              <p className="text-5xl">17</p>
            </div>
            {/* end date div  */}
            {/* balance div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2 flex">
              <div>
                <p>
                  Balance
                  <br />
                  <span className="text-green-500">$184.54</span>
                </p>
              </div>
              <div>
                <BsChevronCompactRight className="text-5xl" />
              </div>
            </div>
            {/* end balance div  */}
          </div>
          {/* end card  */}

          {/* indiv. card  */}
          <div className="flex mt-2">
            {/* date div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2">
              <p className="text-5xl">18</p>
            </div>
            {/* end date div  */}
            {/* balance div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2 flex">
              <div>
                <p>
                  Balance
                  <br />
                  <span className="text-green-500">$184.54</span>
                </p>
              </div>
              <div>
                <BsChevronCompactRight className="text-5xl" />
              </div>
            </div>
            {/* end balance div  */}
          </div>
          {/* end card  */}

          {/* indiv. card  */}
          <div className="flex mt-2">
            {/* date div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2">
              <p className="text-5xl">19</p>
            </div>
            {/* end date div  */}
            {/* balance and transactions divdiv  */}

            <div className="bg-white p-6 rounded-lg shadow-lg flex">
              <div className="mr-4">
                <div className="flex flex-col justify-between">
                  <div>
                    <p>
                      Balance
                      <br />
                      <span className="text-green-500">$55.92</span>
                    </p>
                  </div>
                  <div className="mt-14">
                    <p>
                      <RxTriangleDown className="text-red-500" /> $128.62
                    </p>
                  </div>
                </div>

                {/* end balance div  */}
              </div>
              <div className="flex flex-col">
                <h2 className="underline">Transactions</h2>
                <table>
                  <tr>
                    <td>VZW</td>
                    <td className="text-red-500">$128.62</td>
                  </tr>
                  <tr>
                    <td colSpan={2}>&nbsp;</td>
                  </tr>
                  <tr>
                    <td className="font-bold">total:</td>
                    <td className="text-red-500">$128.62</td>
                  </tr>
                </table>
              </div>
            </div>
          </div>

          {/* end individual card  */}

          {/* indiv. card  */}
          <div className="flex mt-2">
            {/* date div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2">
              <p className="text-5xl">20</p>
            </div>
            {/* end date div  */}
            {/* balance and transactions divdiv  */}

            <div className="bg-white p-6 rounded-lg shadow-lg flex">
              <div className="mr-4">
                <div className="flex flex-col justify-between">
                  <div>
                    <p>
                      Balance
                      <br />
                      <span className="text-green-500">$905.92</span>
                    </p>
                  </div>
                  <div className="mt-14">
                    <p>
                      <RxTriangleUp className="text-green-500" /> $850
                    </p>
                  </div>
                </div>

                {/* end balance div  */}
              </div>
              <div className="flex flex-col">
                <h2 className="underline">Transactions</h2>
                <table>
                  <tr>
                    <td>PayCheck</td>
                    <td className="text-green-500">$850</td>
                  </tr>
                  <tr>
                    <td colSpan={2}>&nbsp;</td>
                  </tr>
                  <tr>
                    <td className="font-bold">total:</td>
                    <td className="text-green-500">$850</td>
                  </tr>
                </table>
              </div>
            </div>
          </div>

          {/* end individual card  */}

          {/* indiv. card  */}
          <div className="flex mt-2">
            {/* date div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2">
              <p className="text-5xl">21</p>
            </div>
            {/* end date div  */}
            {/* balance div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2 flex">
              <div>
                <p>
                  Balance
                  <br />
                  <span className="text-green-500">$905.92</span>
                </p>
              </div>
              <div>
                <BsChevronCompactRight className="text-5xl" />
              </div>
            </div>
            {/* end balance div  */}
          </div>
          {/* end card  */}

          {/* indiv. card  */}
          <div className="flex mt-2">
            {/* date div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2">
              <p className="text-5xl">22</p>
            </div>
            {/* end date div  */}
            {/* balance div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2 flex">
              <div>
                <p>
                  Balance
                  <br />
                  <span className="text-green-500">$905.92</span>
                </p>
              </div>
              <div>
                <BsChevronCompactRight className="text-5xl" />
              </div>
            </div>
            {/* end balance div  */}
          </div>
          {/* end card  */}

          {/* indiv. card  */}
          <div className="flex mt-2">
            {/* date div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2">
              <p className="text-5xl">23</p>
            </div>
            {/* end date div  */}
            {/* balance div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2 flex">
              <div>
                <p>
                  Balance
                  <br />
                  <span className="text-green-500">$905.92</span>
                </p>
              </div>
              <div>
                <BsChevronCompactRight className="text-5xl" />
              </div>
            </div>
            {/* end balance div  */}
          </div>
          {/* end card  */}

          {/* indiv. card  */}
          <div className="flex mt-2">
            {/* date div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2">
              <p className="text-5xl">24</p>
            </div>
            {/* end date div  */}
            {/* balance div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2 flex">
              <div>
                <p>
                  Balance
                  <br />
                  <span className="text-green-500">$905.92</span>
                </p>
              </div>
              <div>
                <BsChevronCompactRight className="text-5xl" />
              </div>
            </div>
            {/* end balance div  */}
          </div>
          {/* end card  */}

          {/* indiv. card  */}
          <div className="flex mt-2">
            {/* date div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2">
              <p className="text-5xl">25</p>
            </div>
            {/* end date div  */}
            {/* balance div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2 flex">
              <div>
                <p>
                  Balance
                  <br />
                  <span className="text-green-500">$905.92</span>
                </p>
              </div>
              <div>
                <BsChevronCompactRight className="text-5xl" />
              </div>
            </div>
            {/* end balance div  */}
          </div>
          {/* end card  */}

          {/* indiv. card  */}
          <div className="flex mt-2">
            {/* date div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2">
              <p className="text-5xl">26</p>
            </div>
            {/* end date div  */}
            {/* balance div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2 flex">
              <div>
                <p>
                  Balance
                  <br />
                  <span className="text-green-500">$905.92</span>
                </p>
              </div>
              <div>
                <BsChevronCompactRight className="text-5xl" />
              </div>
            </div>
            {/* end balance div  */}
          </div>
          {/* end card  */}

          {/* indiv. card  */}
          <div className="flex mt-2">
            {/* date div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2">
              <p className="text-5xl">27</p>
            </div>
            {/* end date div  */}
            {/* balance div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2 flex">
              <div>
                <p>
                  Balance
                  <br />
                  <span className="text-green-500">$905.92</span>
                </p>
              </div>
              <div>
                <BsChevronCompactRight className="text-5xl" />
              </div>
            </div>
            {/* end balance div  */}
          </div>
          {/* end card  */}

          {/* indiv. card  */}
          <div className="flex mt-2">
            {/* date div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2">
              <p className="text-5xl">28</p>
            </div>
            {/* end date div  */}
            {/* balance and transactions divdiv  */}

            <div className="bg-white p-6 rounded-lg shadow-lg flex">
              <div className="mr-4">
                <div className="flex flex-col justify-between">
                  <div>
                    <p>
                      Balance
                      <br />
                      <span className="text-green-500">$1865.92</span>
                    </p>
                  </div>
                  <div className="mt-14">
                    <p>
                      <RxTriangleUp className="text-green-500" /> $960
                    </p>
                  </div>
                </div>

                {/* end balance div  */}
              </div>
              <div className="flex flex-col">
                <h2 className="underline">Transactions</h2>
                <table>
                  <tr>
                    <td>BAH</td>
                    <td className="text-green-500">$800</td>
                  </tr>
                  <tr>
                    <td>VA</td>
                    <td className="text-green-500">$160</td>
                  </tr>
                  <tr>
                    <td colSpan={2}>&nbsp;</td>
                  </tr>
                  <tr>
                    <td className="font-bold">total:</td>
                    <td className="text-green-500">$960</td>
                  </tr>
                </table>
              </div>
            </div>
          </div>

          {/* end individual card  */}

          {/* indiv. card  */}
          <div className="flex mt-2">
            {/* date div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2">
              <p className="text-5xl"> 1</p>
            </div>
            {/* end date div  */}
            {/* balance div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2 flex">
              <div>
                <p>
                  Balance
                  <br />
                  <span className="text-green-500">$1865.92</span>
                </p>
              </div>
              <div>
                <BsChevronCompactRight className="text-5xl" />
              </div>
            </div>
            {/* end balance div  */}
          </div>
          {/* end card  */}

          {/* indiv. card  */}
          <div className="flex mt-2">
            {/* date div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2">
              <p className="text-5xl">2</p>
            </div>
            {/* end date div  */}
            {/* balance div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2 flex">
              <div>
                <p>
                  Balance
                  <br />
                  <span className="text-green-500">$1865.92</span>
                </p>
              </div>
              <div>
                <BsChevronCompactRight className="text-5xl" />
              </div>
            </div>
            {/* end balance div  */}
          </div>
          {/* end card  */}

          {/* indiv. card  */}
          <div className="flex mt-2">
            {/* date div  */}
            <div className="bg-white p-6 rounded-lg shadow-lg mr-2">
              <p className="text-5xl">3</p>
            </div>
            {/* end date div  */}
            {/* balance and transactions divdiv  */}

            <div className="bg-white p-6 rounded-lg shadow-lg flex">
              <div className="mr-4">
                <div className="flex flex-col justify-between">
                  <div>
                    <p>
                      Balance
                      <br />
                      <span className="text-green-500">$676.39</span>
                    </p>
                  </div>
                  <div className="mt-14">
                    <p>
                      <RxTriangleDown className="text-red-500" /> $1,189.53
                    </p>
                  </div>
                </div>

                {/* end balance div  */}
              </div>
              <div className="flex flex-col">
                <h2 className="underline">Transactions</h2>
                <table>
                  <tr>
                    <td>Pay</td>
                    <td className="text-green-500">$800</td>
                  </tr>
                  <tr>
                    <td>Rent</td>
                    <td className="text-red-500">$410</td>
                  </tr>
                  <tr>
                    <td> Car</td>
                    <td className="text-red-500">$579.53</td>
                  </tr>
                  <tr>
                    <td>Down payment</td>
                    <td className="text-red-500">$1,000</td>
                  </tr>
                  <tr>
                    <td colSpan={2}>&nbsp;</td>
                  </tr>
                  <tr>
                    <td className="font-bold">total:</td>
                    <td className="text-red-500">$1,189.53</td>
                  </tr>
                </table>
              </div>
            </div>
          </div>

          {/* end individual card  */}
        </div>

        {/* end container */}
      </section>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
